rewards:
  flirtTool:
    name: flirtTool
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2586
      type: FLINT_AND_STEEL
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"Flirt
          and Steal"}],"text":""}'
        lore:
          - '{"extra":[{"text":"Flirting tool"}],"text":""}'
        enchants:
          CHANNELING: 1